language: node_js
node_js:
  - "8"
before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup target add wasm32-unknown-unknown
  - cargo install wasm-gc

script: npm run build

cache:
  cargo: true
  directories:
    - node_modules

deploy:
  provider: npm
  api_key: "$NPM_TOKEN"
  email: "gary.tierney@gmx.com"
  skip_cleanup: true
  on:
    tags: true
